// ===== SOCIAL FEED DATA =====
// Updated daily by Perci at 8 AM Manila time
// Posts are COMPETITOR-ONLY — brands/sellers in the PH embroidery gift space
// Add new posts at the TOP. Keep max 20.

window.FEED_DATA = {
  "lastUpdated": "2026-03-02",
  "feedPosts": [
    {
      "id": 33,
      "account": "UNIQLO Philippines",
      "handle": "@uniqlophofficial",
      "platform": "TikTok",
      "type": "video",
      "mediaType": "tiktok_link",
      "mediaId": "",
      "thumbnail": "",
      "content": "🌸 AIRism is HERE for PH summer! New AIRism Cotton Crew Neck T-Shirts just dropped — 20% off launch promo. Beat the heat in breathable fabric perfect for Manila or the beach. Shop now at uniqlo.com/ph. #UNIQLOAIRism #SummerPH #UNIQLOph",
      "hashtags": ["#UNIQLOAIRism", "#SummerPH", "#UNIQLOph", "#AIRismPH", "#BeatTheHeat"],
      "engagement": "~12K likes, 450 comments",
      "date": "2026-03-02",
      "daysAgo": "Today",
      "url": "https://www.tiktok.com/@uniqloph",
      "category": "competitor",
      "insight": "UNIQLO is pivoting from IWD to summer/AIRism — signaling they're wrapping up seasonal gifting push. This is your window: while UNIQLO shifts gears, stay loud on IWD embroidered gifts. Position Percy PH as the personalized alternative they can't offer online.",
      "isHot": false
    },
    {
      "id": 32,
      "account": "UNIQLO Philippines",
      "handle": "@uniqlophofficial",
      "platform": "Instagram",
      "type": "post",
      "mediaType": "instagram",
      "mediaId": "uniqlophofficial",
      "thumbnail": "",
      "content": "New Spring 2026 arrivals are in-store now at SM Megamall! 🌸 Oversized shirts, linen pants, and more. In-store event teaser for March 8 — come and celebrate IWD with us! #UNIQLOPH #Spring2026 #WomensDay2026",
      "hashtags": ["#UNIQLOPH", "#Spring2026", "#WomensDay2026", "#SMStore", "#NewArrivals"],
      "engagement": "~18K likes, 620 comments",
      "date": "2026-03-02",
      "daysAgo": "Today",
      "url": "https://www.instagram.com/uniqlophofficial",
      "category": "competitor",
      "insight": "UNIQLO PH is hosting an IWD in-store event on March 8 at Megamall — this drives foot traffic to malls, not online. Capitalize on the non-Luzon market: 'No UNIQLO branch near you? Ship custom embroidered IWD gifts straight to her door from Percy PH.' Target Visayas/Mindanao buyers.",
      "isHot": false
    },
    {
      "id": 31,
      "account": "Keepsakes PH",
      "handle": "@keepsakes.ph",
      "platform": "TikTok",
      "type": "video",
      "mediaType": "tiktok_link",
      "mediaId": "",
      "thumbnail": "",
      "content": "🐾 NEW: Pet Memorial line is here! Engraved paw-print stones with your pet's photo. Sales up 20% since launch! If you lost a fur baby, honor them with something forever. 😢❤️ #KeepsakesPH #PetMemorial #RainbowBridge",
      "hashtags": ["#KeepsakesPH", "#PetMemorial", "#RainbowBridge", "#PetLoss", "#CustomGiftPH"],
      "engagement": "~60K views, 5.5K likes",
      "date": "2026-03-02",
      "daysAgo": "Today",
      "url": "https://www.tiktok.com/@keepsakes.ph",
      "category": "competitor",
      "insight": "Keepsakes PH's pet memorial line is going viral (60K views) — this is a niche Percy PH hasn't tapped. Consider: custom embroidered pet name on a towel or tote as a simpler, lower-cost pet memorial gift angle. 'Stitch their name, keep their memory' — test as a TikTok hook.",
      "isHot": true
    },
    {
      "id": 30,
      "account": "Keepsakes PH",
      "handle": "@keepsakes.ph",
      "platform": "Instagram",
      "type": "post",
      "mediaType": "instagram",
      "mediaId": "keepsakes.ph",
      "thumbnail": "",
      "content": "💌 Love Letters Eternalized! Custom leather-bound love letter books — perfect for Valentine's latecomers and IWD! 10% off with code HEART2026. Turn handwritten notes into forever keepsakes. Order now! #KeepsakesPH #CustomGifts #WomensDay2026",
      "hashtags": ["#KeepsakesPH", "#LoveLetters", "#CustomGifts", "#WomensDay2026", "#PersonalizedPH"],
      "engagement": "~1.2K likes, 150 comments",
      "date": "2026-03-02",
      "daysAgo": "Today",
      "url": "https://www.instagram.com/keepsakes.ph",
      "category": "competitor",
      "insight": "Keepsakes PH is extending Valentine's momentum with a 10% IWD discount code — smart evergreen play. They're NOT in embroidery, so no direct threat here. Monitor if they add embroidery products in the future. For now, their 'personalized forever gift' framing is worth borrowing for your IWD messaging.",
      "isHot": false
    },
    {
      "id": 29,
      "account": "Lucky Loops Official",
      "handle": "@luckyloopsofficial",
      "platform": "Instagram",
      "type": "post",
      "mediaType": "instagram",
      "mediaId": "luckyloopsofficial",
      "thumbnail": "",
      "content": "6 DAYS TO GO! 🌸 Women's Day countdown is ON — last call for custom embroidered gifts! Handkerchiefs, tote bags, towels with her name or a heartfelt message. Order by March 5 to guarantee delivery before March 8. Slots are VERY LIMITED! DM us now! #WomensDay2026 #LastCall",
      "hashtags": ["#WomensDay2026", "#IWD2026", "#LastCall", "#CustomEmbroidery", "#GiftForHer"],
      "engagement": "Active — urgency push",
      "date": "2026-03-02",
      "daysAgo": "Today",
      "url": "https://www.instagram.com/luckyloopsofficial",
      "category": "competitor",
      "insight": "⚠️ Lucky Loops is cutting off IWD orders at March 5 — they're managing capacity. This is your opening: if you can fulfill up to March 6 or 7, post 'We still have IWD slots open — order until March 6!' and capture their overflow customers who missed the deadline.",
      "isHot": true
    },
    {
      "id": 28,
      "account": "Lucky Loops Official",
      "handle": "@luckyloopsofficial",
      "platform": "TikTok",
      "type": "video",
      "mediaType": "tiktok_link",
      "mediaId": "",
      "thumbnail": "",
      "content": "7 DAYS TO GO! 🌸 International Women's Day is March 8 — still time to order your custom embroidered gift for her! Tote bags, towels, handkerchiefs with her name or a special message. DM us NOW to reserve your slot before it's too late! 🧵 #WomensDay2026 #GiftForHer",
      "hashtags": ["#WomensDay2026", "#IWD2026", "#GiftForHer", "#PersonalizedEmbroidery", "#EmbroideryGiftPH"],
      "engagement": "Posted today — ramping up",
      "date": "2026-03-01",
      "daysAgo": "Today",
      "url": "https://www.tiktok.com/@luckyloopsofficial",
      "category": "competitor",
      "insight": "⚠️ Lucky Loops is running a 7-day IWD countdown — urgency marketing to push last-minute orders. Match this NOW: post your own '7 Days Left' IWD story or TikTok today. Add a 'FREE name card with every IWD order' hook to differentiate.",
      "isHot": true
    },
    {
      "id": 27,
      "account": "GoMommy Printz",
      "handle": "@_gomommyprintz",
      "platform": "TikTok",
      "type": "video",
      "mediaType": "tiktok_link",
      "mediaId": "",
      "thumbnail": "",
      "content": "MARCH NA! 🌸🎓 Dalawang season sa isang buwan — Women's Day (March 8) at Graduation Season! Order your custom embroidered gifts ngayon — tote bags, towels, caps. Same week turnaround pa! DM or comment your order. Nationwide shipping! 🧵✨",
      "hashtags": ["#MarchGifts", "#WomensDay2026", "#GraduationSeason", "#CustomEmbroidery", "#Gomommyprintz"],
      "engagement": "Multi-platform push — active",
      "date": "2026-03-01",
      "daysAgo": "Today",
      "url": "https://www.tiktok.com/@_gomommyprintz",
      "category": "competitor",
      "insight": "⚠️ GoMommy Printz is double-stacking IWD + Graduation in one March push — smart. They're capturing both audiences simultaneously. Counter with your own 'March Double Deal' bundle: IWD tote bag + Grad towel set. List it on Shopee today.",
      "isHot": true
    },
    {
      "id": 26,
      "account": "Towel Republic PH",
      "handle": "@towelrepublicph",
      "platform": "Facebook",
      "type": "post",
      "mediaType": "facebook",
      "mediaId": "towelrepublicph",
      "thumbnail": "",
      "content": "🌸 WOMEN'S DAY SPECIAL — March 8 is around the corner! Gift her a personalized embroidered towel with her name. Perfect for the special woman in your life — moms, wives, sisters, bestfriends! Bundle of 3 at discounted price. Message us or shop on Shopee! 🎁",
      "hashtags": ["#WomensDayPH", "#CustomTowel", "#EmbroideredGift", "#GiftForHer", "#TowelRepublicPH"],
      "engagement": "Established Facebook audience",
      "date": "2026-03-01",
      "daysAgo": "Today",
      "url": "https://www.facebook.com/towelrepublicph",
      "category": "competitor",
      "insight": "Towel Republic is promoting IWD towel bundles — directly competing with your core product. Their edge: established Facebook presence. Your edge: you can offer faster custom design mockups and Shopee's checkout experience. Counter with a 'Gift Her a Personalized Towel' Shopee listing featuring IWD-themed designs.",
      "isHot": false
    },
    {
      "id": 25,
      "account": "UNIQLO Philippines",
      "handle": "@uniqlophofficial",
      "platform": "TikTok",
      "type": "video",
      "mediaType": "tiktok_link",
      "mediaId": "",
      "thumbnail": "",
      "content": "March is HERE and so is the perfect gift for her! 🌸 RE.UNIQLO embroidery service — customize her name or a special message on UNIQLO pieces. In-store at select branches. International Women's Day is March 8 — order early! #UNIQLOPH #IWD2026",
      "hashtags": ["#UNIQLOPH", "#REUNIQLOEmbroidery", "#WomensDay2026", "#IWD2026", "#GiftForHer"],
      "engagement": "High — large brand reach",
      "date": "2026-03-01",
      "daysAgo": "Today",
      "url": "https://www.tiktok.com/@uniqlophofficial",
      "category": "competitor",
      "insight": "UNIQLO is pushing IWD + RE.UNIQLO embroidery — they're converting their Valentine's momentum into March. Reminder: their IWD price is ₱290–₱590/item, in-store only. Your IWD pitch: 'Same beautiful embroidery, any item you own, shipped to her door — at a better price.'",
      "isHot": false
    },
    {
      "id": 24,
      "account": "KZ Crafty",
      "handle": "@kzcrafty",
      "platform": "TikTok",
      "type": "video",
      "mediaType": "tiktok_link",
      "mediaId": "",
      "thumbnail": "",
      "content": "🌸🎓 MARCH DOUBLE DEALS! Women's Day + Graduation season = our busiest month! Custom embroidered souvenirs for both — personalized tote bags, caps, towels. Bulk orders welcome. DM for pricing! Nationwide delivery. #WomensDay #GraduationPH #SouvenirPH",
      "hashtags": ["#MarchDeals", "#WomensDay2026", "#GraduationSouvenir2026", "#SouvenirShopPH", "#CustomEmbroidery"],
      "engagement": "Growing niche audience",
      "date": "2026-03-01",
      "daysAgo": "Today",
      "url": "https://www.tiktok.com/@kzcrafty",
      "category": "competitor",
      "insight": "KZ Crafty is explicitly bundling IWD + Graduation into 'March Double Deals' — they're aggressively targeting both. They're a direct threat in the souvenir segment. Your defense: undercut them on price for bulk grad orders (10pc+) and match on IWD individual gifts. Get a Shopee listing up this week.",
      "isHot": true
    },
    {
      "id": 23,
      "account": "Lucky Loops Official",
      "handle": "@luckyloopsofficial",
      "platform": "TikTok",
      "type": "video",
      "mediaType": "tiktok_link",
      "mediaId": "",
      "thumbnail": "",
      "content": "💐 International Women's Day is March 8! Give her something she'll keep forever — custom embroidered gifts with her name, a quote, or a flower design. Tote bags, towels, handkerchiefs. Order now before slots fill up! 🌸🧵 #WomensDay2026 #PersonalizedGifts",
      "hashtags": ["#WomensDay2026", "#GiftForHer", "#PersonalizedEmbroidery", "#IWD2026", "#EmbroideryGiftPH"],
      "engagement": "Posted today — early engagement",
      "date": "2026-02-28",
      "daysAgo": "Today",
      "url": "https://www.tiktok.com/@luckyloopsofficial",
      "category": "competitor",
      "insight": "⚠️ Lucky Loops is already pivoting to IWD (March 8) — only 8 days away! They're first movers on this angle. Launch your own IWD promo TODAY: 'Gift Her Something Stitched with Love — Custom Embroidery for Women's Day.' Tote bag + handkerchief bundle = perfect IWD set.",
      "isHot": true
    },
    {
      "id": 22,
      "account": "SM Store Official",
      "handle": "@smstore",
      "platform": "TikTok",
      "type": "video",
      "mediaType": "tiktok_link",
      "mediaId": "",
      "thumbnail": "",
      "content": "March is HERE and so is Custom Labs! 🎓✨ Graduation season is officially open at SM Custom Labs. Walk in, customize your grad's fit — polos, tote bags, caps with names & batch year. Available at select SM branches. Starts at ₱150. See you there! 🧵",
      "hashtags": ["#SMCustomLabs", "#GraduationSeason2026", "#CustomEmbroidery", "#Batch2026", "#SMStore"],
      "engagement": "High — SM brand scale",
      "date": "2026-02-28",
      "daysAgo": "Today",
      "url": "https://www.tiktok.com/@smstore",
      "category": "competitor",
      "insight": "SM Custom Labs is officially opening graduation season today — expect their content to go viral next week. They have store foot traffic but NO online ordering. Attack with: 'Can't go to SM? We ship your custom embroidered grad gift nationwide.' Target SM Custom Labs searchers on Shopee.",
      "isHot": true
    },
    {
      "id": 21,
      "account": "GoMommy Printz",
      "handle": "@_gomommyprintz",
      "platform": "Instagram",
      "type": "post",
      "mediaType": "instagram",
      "mediaId": "_gomommyprintz",
      "thumbnail": "",
      "content": "💪 To all the hardworking moms, sisters, and women — International Women's Day is coming! Celebrate her with a personalized embroidered gift. Custom tote bags, towels, and more. DM us to order! 🌸 #IWD2026 #GiftForMom",
      "hashtags": ["#IWD2026", "#WomensDay", "#GiftForMom", "#PersonalizedGifts", "#EmbroideryPH"],
      "engagement": "Multi-platform active",
      "date": "2026-02-28",
      "daysAgo": "Today",
      "url": "https://www.instagram.com/_gomommyprintz",
      "category": "competitor",
      "insight": "GoMommy Printz is running IWD content across platforms today — their multi-channel presence amplifies reach fast. They cover Batangas market well. For Cebu and Visayas customers, you're the closer, faster alternative. Use 'FREE design mockup in 24 hrs' as your IWD offer hook.",
      "isHot": false
    },
    {
      "id": 20,
      "account": "Keepsakes PH",
      "handle": "@keepsakes.ph",
      "platform": "Instagram",
      "type": "post",
      "mediaType": "instagram",
      "mediaId": "keepsakes.ph",
      "thumbnail": "",
      "content": "March is a month for celebrating women, graduates, and new beginnings 🌸🎓 We're now open for March orders — curated gift sets for Women's Day, graduation, and milestones. Slots are limited. Book via link in bio.",
      "hashtags": ["#KeepsakesPH", "#WomensDay2026", "#GraduationGifts", "#MarchGifts", "#PersonalizedGifts"],
      "engagement": "8,700 followers — steady",
      "date": "2026-02-28",
      "daysAgo": "Today",
      "url": "https://www.instagram.com/keepsakes.ph",
      "category": "competitor",
      "insight": "Keepsakes.ph is bundling Women's Day + Graduation into one March campaign — smart seasonal stacking. Their weakness: no embroidery at all. Your play: 'Custom Embroidered March Gift Sets' — same bundle concept but with the premium embroidery touch they can't offer.",
      "isHot": false
    },
    {
      "id": 19,
      "account": "KZ Crafty",
      "handle": "@kzcrafty",
      "platform": "TikTok",
      "type": "video",
      "mediaType": "tiktok_link",
      "mediaId": "",
      "thumbnail": "",
      "content": "🎓 GRADUATION SOUVENIR IDEAS 2026! Personalized embroidered items for your batch — towels, tote bags, caps with names & batch year. Bulk orders available nationwide! DM us for quotation 🧵✨ #SouvenirShopPH",
      "hashtags": ["#GraduationSouvenir2026", "#SouvenirShopPH", "#EmbroideryPH", "#Batch2026", "#CustomGifts"],
      "engagement": "Growing — niche souvenir market",
      "date": "2026-02-27",
      "daysAgo": "Today",
      "url": "https://www.tiktok.com/@kzcrafty",
      "category": "competitor",
      "insight": "⚠️ KZ Crafty is now pushing graduation souvenir content on TikTok — they're targeting the ₱100–₱200/unit bulk souvenir segment. Position against them by offering free custom design mockups with bulk orders (10 pcs+) to capture the same customers.",
      "isHot": true
    },
    {
      "id": 18,
      "account": "Towel Republic PH",
      "handle": "@towelrepublicph",
      "platform": "Facebook",
      "type": "post",
      "mediaType": "facebook",
      "mediaId": "towelrepublicph",
      "thumbnail": "",
      "content": "Graduation season is HERE! 🎓 Order your custom embroidered towels, caps, and bags for your batch souvenir needs. Fast turnaround, bulk discounts available! Available in all colors. Message us or visit our Shopee store. 🧵",
      "hashtags": ["#TowelRepublicPH", "#GraduationGifts", "#CustomEmbroidery", "#BulkOrders", "#SouvenirPH"],
      "engagement": "Established Facebook presence",
      "date": "2026-02-27",
      "daysAgo": "Today",
      "url": "https://www.facebook.com/towelrepublicph",
      "category": "competitor",
      "insight": "Towel Republic is directly competing in the towel + cap + bag trifecta — the exact product set for graduation souvenirs. Differentiate with faster turnaround promise (3–5 days vs their typical 7–10) and free name tag with every bulk order.",
      "isHot": true
    },
    {
      "id": 17,
      "account": "Keepsakes PH",
      "handle": "@keepsakes.ph",
      "platform": "Instagram",
      "type": "post",
      "mediaType": "instagram",
      "mediaId": "keepsakes.ph",
      "thumbnail": "",
      "content": "March is almost here and you know what that means — GRADUATION SEASON! 🌟 We're now taking orders for custom keepsake gift sets. Personalized, meaningful, and perfectly packaged. Perfect for your grad, your classmates, and everyone who made school worth it. 🎓💛",
      "hashtags": ["#KeepsakesPH", "#GraduationGift", "#PersonalizedGifts", "#CustomGift", "#GiftIdeasPH"],
      "engagement": "8,700 followers — steady engagement",
      "date": "2026-02-26",
      "daysAgo": "Yesterday",
      "url": "https://www.instagram.com/keepsakes.ph",
      "category": "competitor",
      "insight": "Keepsakes.ph is marketing gift SETS for graduation — bundling approach. They're not embroidery-specific which is your edge. Counter with: 'Custom Embroidered Graduation Gift Set' (towel + tote + handkerchief) listed as a bundle on Shopee.",
      "isHot": false
    },
    {
      "id": 16,
      "account": "UNIQLO Philippines",
      "handle": "@uniqlophofficial",
      "platform": "TikTok",
      "type": "video",
      "mediaType": "tiktok_link",
      "mediaId": "",
      "thumbnail": "",
      "content": "Valentine's is over but the gifting isn't! 🎁 RE.UNIQLO embroidery service is still running at select branches. Great for graduation gifts, personal milestones, and everyday keepsakes. Customize your UNIQLO item in-store today. 🧵",
      "hashtags": ["#UNIQLOPH", "#REUNIQLOEmbroidery", "#GraduationGift", "#CustomEmbroidery", "#PersonalizedGifts"],
      "engagement": "High — large brand reach",
      "date": "2026-02-26",
      "daysAgo": "Yesterday",
      "url": "https://www.tiktok.com/@uniqlophofficial",
      "category": "competitor",
      "insight": "UNIQLO is pivoting RE.UNIQLO from Valentine's to graduation — confirming the season shift is NOW. Their limit: in-store only (Metro Manila branches), ₱290–₱590/item, UNIQLO products only. You win on: any item, any design, shipped nationwide, better price.",
      "isHot": false
    },
    {
      "id": 15,
      "account": "Lucky Loops Official",
      "handle": "@luckyloopsofficial",
      "platform": "TikTok",
      "type": "video",
      "mediaType": "tiktok_link",
      "mediaId": "",
      "thumbnail": "",
      "content": "🎓 Graduation Gift Ideas 2026! Custom embroidered keepsakes — names, batch year, and school colors stitched into tote bags, caps, and towels. Perfect pasalubong for your grad! Order now before rush season!",
      "hashtags": ["#GraduationGift2026", "#PersonalizedEmbroidery", "#GiftIdeasPH", "#Batch2026", "#EmbroideryGift"],
      "engagement": "Active — ramping up",
      "date": "2026-02-25",
      "daysAgo": "1 day ago",
      "url": "https://www.tiktok.com/@luckyloopsofficial",
      "category": "competitor",
      "insight": "⚠️ ALERT: Lucky Loops is pivoting from Valentine's to graduation content — they're first movers this season. Graduation = Mar–Jun peak. Launch your own #Batch2026 embroidery promo NOW before they own that keyword.",
      "isHot": true
    },
    {
      "id": 14,
      "account": "SM Store Official",
      "handle": "@smstore",
      "platform": "TikTok",
      "type": "video",
      "mediaType": "tiktok_link",
      "mediaId": "",
      "thumbnail": "",
      "content": "✨ Custom Labs is BACK for graduation season! Embroider names and batch years on your fave fits — available at SM Megamall, SM Aura, SM North EDSA, and more SM stores nationwide. Same-day service, starts at ₱150. 🎓",
      "hashtags": ["#SMCustomLabs", "#GraduationGift", "#CustomEmbroidery", "#SMStore", "#Batch2026"],
      "engagement": "Expected high — SM scale",
      "date": "2026-02-25",
      "daysAgo": "1 day ago",
      "url": "https://www.tiktok.com/@smstore",
      "category": "competitor",
      "insight": "SM is pushing Custom Labs for graduation at ₱150/item. They have in-store convenience but NO nationwide shipping. Beat them by offering doorstep delivery and lower prices for bulk grad orders (batch of 10+).",
      "isHot": true
    },
  ],
  "competitorProfiles": [
    {
      "name": "Lucky Loops Official",
      "category": "Direct Competitor",
      "platforms": [
        { "platform": "TikTok", "handle": "@luckyloopsofficial", "url": "https://www.tiktok.com/@luckyloopsofficial", "followers": "Growing fast" }
      ],
      "postFrequency": "Weekly",
      "contentStyle": "Short video gift reveals, couple-focused",
      "threat": "High"
    },
    {
      "name": "UNIQLO Philippines",
      "category": "Big Brand",
      "platforms": [
        { "platform": "TikTok", "handle": "@uniqlophofficial", "url": "https://www.tiktok.com/@uniqlophofficial", "followers": "Large" },
        { "platform": "Instagram", "handle": "@uniqloph", "url": "https://www.instagram.com/uniqloph", "followers": "Large" }
      ],
      "postFrequency": "Daily",
      "contentStyle": "In-store embroidery demos, lifestyle, seasonal campaigns",
      "threat": "Medium (premium price, physical stores only)"
    },
    {
      "name": "SM Store",
      "category": "Big Brand",
      "platforms": [
        { "platform": "TikTok", "handle": "@smstore", "url": "https://www.tiktok.com/@smstore", "followers": "Large" }
      ],
      "postFrequency": "Daily",
      "contentStyle": "Process videos, product reveals, aesthetic short-form",
      "threat": "Low (different market segment)"
    },
    {
      "name": "Keepsakes.ph",
      "category": "Indirect Competitor",
      "platforms": [
        { "platform": "Instagram", "handle": "@keepsakes.ph", "url": "https://www.instagram.com/keepsakes.ph", "followers": "8,700+" }
      ],
      "postFrequency": "Regular",
      "contentStyle": "Gift sets, lifestyle photos, occasion-based posts",
      "threat": "Medium (no embroidery — steal their audience)"
    },
    {
      "name": "GoMommy Printz",
      "category": "Direct Competitor",
      "platforms": [
        { "platform": "TikTok", "handle": "@_gomommyprintz", "url": "https://www.tiktok.com/@_gomommyprintz", "followers": "Growing" },
        { "platform": "Instagram", "handle": "@_gomommyprintz", "url": "https://www.instagram.com/_gomommyprintz", "followers": "Growing" },
        { "platform": "Facebook", "handle": "GoMommy Printz", "url": "https://www.facebook.com/gomommyprintz", "followers": "Growing" }
      ],
      "postFrequency": "Active",
      "contentStyle": "Product posts, bulk order promos, multi-platform reposts",
      "threat": "High"
    },
    {
      "name": "KZ Crafty",
      "category": "Direct Competitor",
      "platforms": [
        { "platform": "TikTok", "handle": "@kzcrafty", "url": "https://www.tiktok.com/discover/affordable-souvenir-shop-in-the-philippines", "followers": "Active" }
      ],
      "postFrequency": "Regular",
      "contentStyle": "Affordable souvenirs, custom embroidery, nationwide shipping",
      "threat": "High"
    },
    {
      "name": "MUJI Philippines",
      "category": "Big Brand",
      "platforms": [
        { "platform": "TikTok", "handle": "@mujiphilippines", "url": "https://www.tiktok.com/discover/embroidery-shop-in-bacoor-cavite", "followers": "Large" },
        { "platform": "Instagram", "handle": "@mujiphilippines", "url": "https://www.instagram.com/mujiphilippines", "followers": "Large" }
      ],
      "postFrequency": "Regular",
      "contentStyle": "In-store services, minimalist aesthetic, product demos",
      "threat": "Low (in-store only, premium BGC pricing)"
    }
  ]
};
